b:
    resource: "@BBundle/Resources/config/routing.yml"
    prefix:   /

b_translation:
    path:     /traduction/{name}
    defaults: { _controller: BBundle:Advert:translation }

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
